### ISSUE TITLE
Bounty System?

### ISSUE THREAD

**Issue by ChewyAurora** [DrHenny/668-Issues#36]
Believe we had this for myriad but never got really used

This system would allow users to place a bounty on players they want to get killed.

This system could reward the player who kills the bounty holding user as well as the bounty holder by getting extra points for killing with a bounty.

> How would you like this to work?
> 
> Would you like to give them old bounty hunter skulls to show they are being targeted / have a bounty?
**Yes some sort of highlight would be good**
> What would you like to set the coin cap to?
**Maybe maximum of 100m or 500m bounties?**
> How much of the reward do you want the player to receive? perhaps 75%? 25% tax?
**I like 75/25**
> How would they be able to set the bounty? I assume talk to an NPC and type in the players name then an amount of coins?
**yes**

**Comment by DrHenny** [comment]
finished
