### ISSUE TITLE
HotKey Interfaces pictures

### ISSUE THREAD

**Issue by BigMeechrs** [DrHenny/668-Issues#54]
https://media.discordapp.net/attachments/1295876994025652334/1299530837485813820/ynIHlPm.png?ex=671e32a7&is=671ce127&hm=8be8716f7803998a9a676c6e6f53dbbd7f0ad8f01805c2c28f65aadb3bb99199&=&format=webp&quality=lossless&width=1116&height=676

https://media.discordapp.net/attachments/1295876994025652334/1299530805122568202/YdPSBWv.png?ex=671e32a0&is=671ce120&hm=af55165e5f03e49acfa679614d922c06b0e4ed982c9e33940c90b31453a897ce&=&format=webp&quality=lossless&width=550&height=333

**Comment by DrHenny** [comment]
closed, invalid urls, no media, no description.
